### ISSUE TITLE
Turn valuations page into a profit margin calculator

### ISSUE THREAD

**Issue by volkyeth** [optionhq/index-wallets-game#13]
The players should be able to calculate a profit margin comparing how much they'll sell their products for to how much they'll pay to restock with providers

**Comment by cnrmck** [comment]
Mock
<img width="429" alt="image" src="https://github.com/optionhq/index-wallets-game/assets/22061955/d8c28f2e-d404-4764-ae25-6b480a6678c3">

**Comment by volkyeth** [comment]
Solved by profit margin chart
<img width="382" alt="image" src="https://github.com/user-attachments/assets/4c24458e-6d54-4ceb-8ef7-d6054e732ea2">
