### ISSUE TITLE
Bug: shouldn't be able to set valuations outside the range

### ISSUE THREAD

**Issue by volkyeth** [optionhq/index-wallets-game#22]
It's possible to set valuations outside the valuation amplitude config by inputting them in the text field

**Comment by cnrmck** [comment]
I think it’s the other way around: it should be easier for everyone to set their valuations outside the range and easier to see other ppls valuations when they’re way out of the range. Why should we arbitrarily limit the valuation range? Bitcoin has a valuation of 50k per token, is that not ok?

**Comment by volkyeth** [comment]
What's the use-case for setting extreme valuations, in the context of the game? You found out it was possible and used it to affect your score, since it was based on your own valuation of your tokens, but we've since agreed that the score should be based on market valuations.

Other use-cases I can think of are impractical for serious play, since extreme valuations just prevent you from being able to transact with other players. So that should only be the case for jests and amusement.

On the other hand, there are some UI challenges to solve for extreme valuations:
- They change the scale of charts and make them illegible
- They produce huge value strings that can't fit on the tables

So I think we're probably better off not supporting that, since we have limited resources and I can't picture a situation where allowing for that would provide us useful data. Is there some important use case for that that I might be missing?

**Comment by cnrmck** [comment]
> Is there some important use case for that that I might be missing?
Yeah, if most players set a valuation of 20 for a specific token then they all get benefit from the public goods funding, the charts will be legible (their valuations will all be within a similar domain) and it won't produce huge value strings.

**Comment by volkyeth** [comment]
That's one extreme scenario where that's the case. Every other in-between state has the problems I mentioned, so the problem remains.

And I still can't picture an honest, serious game where that would happen without breaking the market. Players get their income in USD, which is fixed at a valuation of 1, so devaluing the USD to the extreme in relation to another token is to their detriment.

I'm still not convinced supporting arbitrary valuations is a good use of resources

**Comment by cnrmck** [comment]
If someone has very few tokens of a single denomination the only way to actually create an incentive for them is to value those tokens very highly.

**Comment by volkyeth** [comment]
Ok, so this behaves as intended
