### ISSUE TITLE
Bug: BEST deal

### ISSUE THREAD

**Issue by cnrmck** [optionhq/index-wallets-game#29]
In this picture, you can see that the spatula has a better valuation than the cutting board, but a worse valuation than the pot.

Nonetheless, for some reason the spatula is being told they're the best price
![image](https://github.com/user-attachments/assets/4e039354-afcd-4a64-a3e9-4047968da94d)

Weirdly, moving the valuation one tick to the left (from 0.2 to 0.1) gets rid of the BEST indicator.
![image](https://github.com/user-attachments/assets/0f28b280-69b1-49cb-8a4a-bc6316414de4)

I've verified that even with 0.2, Bob is not the best price:
<img width="690" alt="image" src="https://github.com/user-attachments/assets/842a4977-7c92-4fba-b261-4d38a641b05f">

This was with the game code: HQX0AF

Additional Note:
When two valuations are the same, it shouldn't say BEST. If you want, it could say, "TIE" or "MATCH", but it's not the BEST.

**Comment by volkyeth** [comment]
Checking the bug.

Re:
> When two valuations are the same, it shouldn't say BEST. If you want, it could say, "TIE" or "MATCH", but it's not the BEST.

Well, it IS the best. The best value you can get can be offered by more than one vendor, and that does not keep it from being the best. I think using TIE/MATCH will make it more confusing.

**Comment by cnrmck** [comment]
Ok I buy it.
