### ISSUE TITLE
Update tooltip to make player name more visible

### ISSUE THREAD

**Issue by cnrmck** [optionhq/index-wallets-game#30]
Often the player asks, "who is the rolling pin again"

![image](https://github.com/user-attachments/assets/e9afed60-0a75-4ba7-a111-d09b882222a4)

**Comment by volkyeth** [comment]
Though ask.

The ceil for UI density is the iPhone 4:
<img width="321" alt="image" src="https://github.com/user-attachments/assets/0da1f536-6e6c-4647-bc68-bba3624b1b0f">

It's already packed like a can of sardines. Can't fit the names under the icons in that spot
Moreover, whenever displaying user-inputted data, you must have enough spare space for lengthy values to render.

TBH I think the tooltip is enough. It already conveys this information in a way that works within the constraints above
<img width="321" alt="image" src="https://github.com/user-attachments/assets/68a752c2-a304-4b18-bc8c-44c676e989cd">

**Comment by cnrmck** [comment]
This is a good point.

It seems the tooltip hasn't been sufficient. The problem is that people don't know the name of the person associated with the icon. So there's a lot of asking, "Who is the spoon?" 

Maybe it could be fixed by tweaking the tooltip?

![image](https://github.com/user-attachments/assets/a60b4d9a-82d8-40ae-be98-ab96250bdd17)
