### ISSUE TITLE
Change donate icon

### ISSUE THREAD

**Issue by cnrmck** [optionhq/index-wallets-game#37]
Players keep thinking the donate page is the pay page. 

![image](https://github.com/user-attachments/assets/ccb4fc29-a673-4746-9057-65244ed89cd9)

Perhaps change it to a simple heart
![image](https://github.com/user-attachments/assets/d5429262-b911-46bf-bc77-124a1bd52454)

**Comment by volkyeth** [comment]
❤️ is usually associated with favorites/liked

Let's try this one, instead:
<img width="51" alt="image" src="https://github.com/user-attachments/assets/735753e2-b420-48bd-a7a8-8ec073d31e86">
