### ISSUE TITLE
Donations should show the total amount of tokens returned (not the additional amount)

### ISSUE THREAD

**Issue by connormcmk** [optionhq/index-wallets-game#38]
It's especially confusing because the price is higher AND the tokens are lower, which is double counting. Just leave it as 20.
![image](https://github.com/user-attachments/assets/8d4c0cf3-39f7-4b7c-a377-b558007472c4)

**Comment by volkyeth** [comment]
But displaying 20 tokens acquired is also misleading. They will see that in their history and expect to have their balance increased by 20, but that's not the case.

Truth is the mechanic itself is confusing, paying and being rewarded in the same token. We need to find a better way of conveying that.

**Comment by cnrmck** [comment]
> They will see that in their history and expect to have their balance increased by 20, but that's not the case.
Nope, they saw their history and when they opened it they saw that they spent 9 TOKEN to get 20 TOKEN, and that was good enough for them
