### ISSUE TITLE
BUG: Donations say they cost 0

### ISSUE THREAD

**Issue by brunowowk** [optionhq/index-wallets-game#64]
![Image](https://github.com/user-attachments/assets/66a122fc-dd1c-4bba-ad69-52d126735f77)

**Comment by volkyeth** [comment]
Actually, that's how much the 20 tokens you acquire are worth, according to your network valuations.
The cost of the donation is up top:

![Image](https://github.com/user-attachments/assets/0371b4d1-c6cd-41b1-9b31-6686bc2a72d2)

if I change it to `20 PUB (worth ⱡ0.00)`, is that enough?
